### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [1]:
import numpy as np

In [45]:
def desc_np_array(n):
    arr = np.arange(0, n)
    arr_rev = arr[n::-1]
    return arr_rev

In [46]:
a = desc_np_array(5)
a

array([4, 3, 2, 1, 0])

### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали

In [52]:
def desc_np_matrix(n):
    diagonal = desc_np_array(n)
    matrix = np.diag(diagonal)
    return matrix

In [53]:
m = desc_np_matrix(5)
m

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

### Задание 3

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0

In [2]:
import pandas as pd

In [3]:
movies = pd.read_csv('ml-latest-small/movies.csv')
ratings = pd.read_csv('ml-latest-small/ratings.csv')
links = pd.read_csv('ml-latest-small/links.csv')

In [30]:
# movies.head()
# ratings.head()
# links.head()

In [31]:
five_rated = ratings[ratings['rating'] == 5.0]
five_rated.head()

userId  movieId  rating  timestamp
3       1       47     5.0  964983815
4       1       50     5.0  964982931
6       1      101     5.0  964980868
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [48]:
top_rated_distinct = five_rated.groupby('movieId').size().sort_values(ascending=False).head(1)
top_rated_distinct = top_rated_distinct.to_frame('n_fives')
top_rated_distinct

n_fives
movieId         
318          153

In [49]:
# Ответ

joined_top = movies.merge(top_rated_distinct, on='movieId', how='inner')
joined_top

movieId                             title       genres  n_fives
0      318  Shawshank Redemption, The (1994)  Crime|Drama      153

### Задание 4

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity

In [64]:
power = pd.read_csv('power.csv')
power.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [92]:
baltics = power[((power['country'] == 'Estonia') | (power['country'] == 'Latvia') | (power['country'] == 'Lithuania')) 
                          & (power['quantity'] > 0) 
                          & (power['year'] >= 2005) & (power['year'] <= 2010) 
                          & ((power['category'] == 4) | (power['category'] == 12) | (power['category'] == 21))]
baltics.head()

country  year  quantity  category
10617    Estonia  2008       1.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4
11158  Lithuania  2006       1.0         4
11159  Lithuania  2005       1.0         4

In [93]:
# Ответ

sum_quantity = baltics['quantity'].sum()
sum_quantity

240580.0

### Задание 5

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [13]:
# коэффициенты при переменных в левой части уравнения

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])

In [14]:
b = np.array([4, 12, -3])

In [15]:
# решение

from numpy import linalg

In [16]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [17]:
# проверка верности

np.allclose(np.dot(a, linalg.solve(a, b)), b)

True